FROM maven:3.9.5-eclipse-temurin-17 AS builder
WORKDIR /app

COPY pom.xml .

COPY ./src ./src

RUN mvn dependency:go-offline

RUN mvn clean install -DskipTests

FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar

ARG APP_NAME
ARG CONTEXT_PATH
ARG CORS_ORIGIN
ARG DS_DRIVER_CLASS_NAME
ARG DS_URL
ARG DS_USERNAME
ARG DS_PASSWORD
ARG EXPIRE_LENGTH
ARG JPA_DIALECT
ARG PROFILES_ACTIVE
ARG SECRET_KEY
ARG SPRINGDOC_PATHS

ENV APP_NAME=${APP_NAME} \
    CONTEXT_PATH=${CONTEXT_PATH} \
    CORS_ORIGIN=${CORS_ORIGIN} \
    DS_DRIVER_CLASS_NAME=${DS_DRIVER_CLASS_NAME} \
    DS_URL=${DS_URL} \
    DS_USERNAME=${DS_USERNAME} \
    DS_PASSWORD=${DS_PASSWORD} \
    EXPIRE_LENGTH=${EXPIRE_LENGTH} \
    JPA_DIALECT=${JPA_DIALECT} \
    PROFILES_ACTIVE=${PROFILES_ACTIVE} \
    SECRET_KEY=${SECRET_KEY} \
    SPRINGDOC_PATHS=${SPRINGDOC_PATHS}

ENTRYPOINT ["java", "-jar", "app.jar"]