version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  auth-service:
    build:
      context: .  # Caminho relativo do diretório atual
    environment:
      APP_NAME: auth-service
      CONTEXT_PATH: /auth-service/api
      CORS_ORIGIN: http://192.168.*.*:*, http://www.granaflow.local:*, http://localhost:*
      DS_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      DS_URL: jdbc:mysql://mysql:3306/auth_service?useTimezone=true&serverTimezone=UTC
      DS_USERNAME: root
      DS_PASSWORD: root
      EXPIRE_LENGTH: '3600000'
      JPA_DIALECT: org.hibernate.dialect.MySQL57Dialect
      PROFILES_ACTIVE: dev
      SECRET_KEY: hc08sjjSnsqVYmtp/gfuQRMeQNXDRo6gkLWT50p8rbQ=
      SPRINGDOC_PATHS: /auth-service/**,/auth/**,/api/**/v1/**
    networks:
      - app-network
    ports:
      - "8086:8086"
    depends_on:
      - mysql
    volumes:
      - auth-service-data:/app/data

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: auth_service
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  auth-service-data:
  mysql-data:
