version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  auth-service:
    build:
      context: .
    environment:
      APP_NAME: ${APP_NAME}
      CONTEXT_PATH: ${CONTEXT_PATH}
      CORS_ORIGIN: ${CORS_ORIGIN}
      DS_DRIVER_CLASS_NAME: ${DS_DRIVER_CLASS_NAME}
      DS_URL: ${DS_URL}
      DS_USERNAME: ${DS_USERNAME}
      DS_PASSWORD: ${DS_PASSWORD}
      EXPIRE_LENGTH: ${EXPIRE_LENGTH}
      JPA_DIALECT: ${JPA_DIALECT}
      PROFILES_ACTIVE: ${PROFILES_ACTIVE}
      SECRET_KEY: ${SECRET_KEY}
      SPRINGDOC_PATHS: ${SPRINGDOC_PATHS}
    networks:
      - app-network
    ports:
      - "8086:8086"
    depends_on:
      - mysql
    volumes:
      - auth-service-data:/app/data

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app-network
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  auth-service-data:
  mysql-data:
